### ISSUE TITLE
Col log sound not playing

### ISSUE THREAD

**Issue by Raisoshi** [m0bilebtw/c-engineer-completed#10]
Not sure why, level up completed works, but I'm not getting the col log slot completed voice message anymore as of a few weeks ago. Tried installing the new tedious plugin which seems to be based off this one today and it doesn't work either, is the sound sent in a different way or something?

**Comment by m0bilebtw** [comment]
First thing to check is do you have in-game new collection log item notification setting turned on? That's the way that this plugin (and the Tedious one if it is a fork of this one) detects a new collection log item

**Comment by m0bilebtw** [comment]
Will close soon without any replies
