### ISSUE TITLE
Death sound

### ISSUE THREAD

**Issue by tempoross** [m0bilebtw/c-engineer-completed#12]
Hey there! 

This isn't really an issue but it is the only way i know to reach out, 

I'm here with a request, if there is a possibility for you to create a similar one to this one, but with a friend/dovydas saying "byee"
i'm not knowledgeable in programming, so either as a request or to help me build one up from scratch

**Comment by m0bilebtw** [comment]
If you just want this for yourself, the easiest thing to do is find your `.runelite` folder and find the folder within that where this plugin stores its sounds. If you replace one with your own file (make sure it is a .wav) with the EXACT same name, it will use your sound instead. If you ever want to go back to the plugin sound, just delete the file and it will re-download the default sound next time it starts up.

**Comment by m0bilebtw** [comment]
Please let me know if this was sufficient or if you need more info!
