### ISSUE TITLE
Sounds not working on Main acc

### ISSUE THREAD

**Issue by spartan9154** [m0bilebtw/c-engineer-completed#13]
Hi, I was wondering if you know a fix for the sounds working on my alt, but not on the main when playing side by side or just one at a time. I've reinstalled the plug0in and runelite multiple times including deleting the external plugin files. Any help is appreciated!

**Comment by m0bilebtw** [comment]
Not sure, will have to investigate a bit.
Is it for all the sounds or only specific ones?

**Comment by m0bilebtw** [comment]
Check your in-game settings on your main account, ensure that collection log notifications are on. The plugin can only detect new collection log items via the in-game notification for them, so if that's off (or for some reason the game fails to send that notification), then collection log sounds will not play.

**Comment by spartan9154** [comment]
Chat notifications were NOT on, but the other thing was. I bet that's the issue. Will update if it works :D TYSM for your time!

**Comment by spartan9154** [comment]
IT WORKS!!!!!!!!!!!!!
