### ISSUE TITLE
Optional Voices

### ISSUE THREAD

**Issue by jdanthdavis** [m0bilebtw/c-engineer-completed#15]
I'm interested in adding the option to use different streamer voices instead of just c-engineer. It'd be a little strange to odd multiple options for the voice when the plugin is called c-engineer-completed. Would you mind if I used your code to make my own twist? I'm not exactly sure how to go about something like this.

**Comment by m0bilebtw** [comment]
If you want this just for yourself, look at replacing the sound files it uses (explained in the README)
If you want to make one available for others to download from the plugin hub, see #6

**Comment by jdanthdavis** [comment]
It would be used by some others as well. I'll go ahead make it a separate plugin. I'll be sure to give credit to you as well!

Thanks!
