### ISSUE TITLE
Altscape and C-engineer announcements

### ISSUE THREAD

**Issue by jjyach14** [m0bilebtw/c-engineer-completed#16]
Collection log announcements are broken and I have seen this reported on another person's altscape experience: https://www.reddit.com/r/2007scape/comments/rqrwic/help_with_the_c_engineer_plugin/

My experience is that the question and level up announcements work, but the collection log audio is not coming through on my alt account. Whether my main account is open or not, the plug-in seems broken. I assume it is related to cached data from the main? Perhaps it disrupts new accounts collection logging the same items?

**Comment by m0bilebtw** [comment]
Check #13, or #8

**Comment by m0bilebtw** [comment]
Great, glad to hear it!
