### ISSUE TITLE
[Future Request] Boss PB

### ISSUE THREAD

**Issue by ETalanian** [m0bilebtw/c-engineer-completed#17]
I'd love to have a trigger for PBs.  I'm a big fan of using this plugin with custom sounds and would love to use either the Beetle Adventure Racing "New Record" sound or the Mario Party "New Record" sound whenever I get a new PB on a boss/raid.

**Comment by m0bilebtw** [comment]
Thanks for the suggestion - I've been discussing enhancements with C and we're not looking to add PB detection for other bosses
This would be better suited to another plugin that is not specific to C
