### ISSUE TITLE
Plugin not working when using official jagex launcher

### ISSUE THREAD

**Issue by Kolobolokin** [m0bilebtw/c-engineer-completed#18]
Title. Since I switched to the jagex launcher -> runelite, it seems like I no longer hear C Engineer's beautiful voice. Is this a known issue, and if not can this be investigated?

**Comment by Kolobolokin** [comment]
I didn't see anything out-of-the-ordinary in the sound files (though I think I spoiled myself for some of the easter egg lines).

The only things I'm seeing in my client logs are that the plugin is successfully loaded. Nothing in the launcher logs, which is to be expected. The logs go back 30 days, and everything seems fine.

I've uninstalled and reinstalled the plugin, relaunched the client, restarted the pc, no dice.

**Comment by m0bilebtw** [comment]
Any further news on this @Kolobolokin?

**Comment by Kolobolokin** [comment]
I actually confirmed just now that, for sure, the collection log doesn't work. Finally got something new, no dice

**Comment by Kolobolokin** [comment]
And, to be clear, the audio file isn't corrupted or anything in the folder

**Comment by Kolobolokin** [comment]
Confirmed that the haircut and lumbridge staircase work, confirmed that level up works, and confirmed that death noise works. I can't do quest or achievement diary on my account, and I'm about 90% sure that combat task works. Seems to just be collection log, and I can't figure out why.

**Comment by m0bilebtw** [comment]
Enable this

https://user-images.githubusercontent.com/62370532/208992085-e2c07494-d8bb-489e-b7f3-ed538175acbc.png

**Comment by Kolobolokin** [comment]
Interesting. That seems to have fixed it - did something change where that needs to be enabled?

**Comment by m0bilebtw** [comment]
That has always needed to be enabled, quite possible that switching to jagex launcher did something funky with your in game settings where some persisted and some didn't

**Comment by Kolobolokin** [comment]
Huh, weird! Alright, well thanks for the help

**Comment by Kolobolokin** [comment]
Interestingly, I just spoke with one of my buddies and this isn't an isolated thing. Seems like if you went from runelite to jagex launcher, you need to go back in and enable that setting. Pretty weird

**Comment by m0bilebtw** [comment]
That is good to know - explains the increase in people recently complaining that collection log announcement isn't working. I already have an update waiting for runelite dev approval that adds a warning if the setting is on for the plugin but off in the game settings to remind users to fix it. Hopefully that gets approved sooner rather than later!
