### ISSUE TITLE
Collection Log Completed Sound Not Playing After Changing

### ISSUE THREAD

**Issue by PapaC95** [m0bilebtw/c-engineer-completed#21]
I have recently changed the sounds source files for many of the sounds within the plugin. Everything other than the collection log sound seems to be playing correctly.

I've taken the following troubleshooting steps:

1. Verified the plugin is on while receiving a collection log notification.
2. Verified the source file is a .wav file.
3. Verified the audio of the file.
4. Reinstalled Runelite and the C Engineer Plugin as well.
5. Verified chat notifications are enabled in Settings

If there are any other troubleshooting steps I should be taking, please let me know. Thanks.

**Comment by m0bilebtw** [comment]
Is there anything relevant in the logs? `client.log` in `C:\Users\<username>\.runelite\logs`

The plugin is on, but is the collection log specific setting within the plugin settings on?
![image](https://github.com/m0bilebtw/c-engineer-completed/assets/62370532/09635da2-34a8-474a-8d1b-ecaf2760b25a)

What is the exact name of the file you are trying to use that isn't playing?

**Comment by PapaC95** [comment]
I checked the logs, and don't see anything that specifically mentions failing to load the plugin. (There is a lot of info here, so I may have overlooked something.)

I have everything in the plugin checked, and the "New collection log entry" box is checked as well.

The file name in the folder is: ColLogSlotCompleted_r1
I copied the previous file name exactly as it was prior.

**Comment by m0bilebtw** [comment]
Are you comfortable sharing the sound file and log file with me? I am `spoody.` on discord if so

**Comment by m0bilebtw** [comment]
Discussed on discord, I believe this was a case of an unsupported file (despite being `.wav`, there are nuances that sometimes java `clip` does not like).

For anyone finding this in the future - if you are **sure** your settings are correct, it's probably an issue with the sound file itself. It's not feasible for me to manually resolve invalid file issues, so for reference: I use 'ardour' to export 16 bit wav files.
