### ISSUE TITLE
In-Compatable Now

### ISSUE THREAD

**Issue by VileVampyre** [m0bilebtw/c-engineer-completed#25]
Says on runelite  needs to be updated?

**Comment by m0bilebtw** [comment]
Thanks for reporting. I am aware, but am not home from work yet. Hold tight

**Comment by VileVampyre** [comment]
Oh no worries, just wanted to make sure you saw. Thank you

**Comment by m0bilebtw** [comment]
It seems fine - when did you last restart your client?

**Comment by VileVampyre** [comment]
That fixed it :)

**Comment by m0bilebtw** [comment]
Glad to hear it!
