### ISSUE TITLE
[FEATURE REQUEST] A ceng sound clip for when a superior foe spawns

### ISSUE THREAD

**Issue by cwilson21** [m0bilebtw/c-engineer-completed#30]
Would be nice to have a sound clip played for when a superior foe spawns while doing slayer, if cengineer would like to add another sound clip.

**Comment by m0bilebtw** [comment]
Thanks for the suggestion - I've been discussing enhancements with C and we're not looking to add announcements to superior spawns in this plugin though there may be a similar plugin that can offer this functionality
