### ISSUE TITLE
[Bug] Achievement diary completion chat message spam

### ISSUE THREAD

**Issue by SandroVA** [m0bilebtw/c-engineer-completed#4]
If you complete an achievement diary and have the show fake public chat message option on it spams you with messages.
https://cdn.discordapp.com/attachments/841732389369413652/888150442499002388/unknown.png

As you can see I've received 200 of these messages.

**Comment by m0bilebtw** [comment]
Which diary was completed when this happened, in case that ends up being important?

**Comment by SandroVA** [comment]
Its still going btw LOL
https://cdn.discordapp.com/attachments/841732389369413652/888159822275571712/unknown.png

I was doing various wildy meds. Not sure which exactly

**Comment by m0bilebtw** [comment]
Oh dear 😅 does it stop if you disable and re-enable the plugin?

**Comment by SandroVA** [comment]
yep haha

**Comment by m0bilebtw** [comment]
Have just been able to reproduce this on my alt with a fairly slow spam, roughly once per minute right now. Will look more into it.

**Comment by m0bilebtw** [comment]
@SandroVA which OS were you running when this happened? And related, did you hear the sound clips play or not?

**Comment by SandroVA** [comment]
Windows. Sadly though I don't have sounds on my work computer (which is what I was using at the time)

**Comment by m0bilebtw** [comment]
Does the computer have no sound capability or do you mean it was muted or similar?

**Comment by SandroVA** [comment]
No headphones or speakers connected to it.

**Comment by m0bilebtw** [comment]
Okay, I'm not 100% why you'd run in to this issue on windows, but on my linux box where pulseaudio commonly fails to play the sound clips, I was getting this same behaviour - I had just never stayed logged in long enough while testing for the repeat messages to come up. I've changed the order of things and it seems to have fixed the repeat messages issue on my linux box, so I'll push those changes closing this issue, so hopefully it'll be fixed after the runelite people accept the plugin update. If it continues *after the plugin hub update has come through* then comment again here and I'll re-open and keep looking into it.

**Comment by SandroVA** [comment]
Perfect thanks bud. Have a good one and thanks for the plugin 👍 
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.
C Engineer: Bug fix: completed.

**Comment by m0bilebtw** [comment]
Relevant code change: 3188b33c5819f0bbe3f66eb766172ab1052ee58e

**Comment by m0bilebtw** [comment]
This update has now been accepted on plugin-hub

https://github.com/runelite/plugin-hub/pull/1873
