### ISSUE TITLE
possible try to get a skill specs version?

### ISSUE THREAD

**Issue by NsaneCowboy** [m0bilebtw/c-engineer-completed#6]
would be just like c engineer with using skill specs voice for completion of quest and diarys and such but most of all the iconic dead voiceover

**Comment by m0bilebtw** [comment]
I won't be looking to add other voices to this plugin, but as per the LICENSE file the code can be used to make a separate plugin if you wish, which would essentially require you just replace the sound files themselves and change the plugin name, tags, etc.
