### ISSUE TITLE
[Feature Request] Ability to change sound effects for notifications.

### ISSUE THREAD

**Issue by gwenstefani991** [m0bilebtw/c-engineer-completed#9]
After awhile, the C Engineer audio cues can become tiresome. What if we were able to have a folder where we rename a .wav to the same as the original plugin eg ColLogSlotCompleted_r1.wav to change the audio cue. This would allow greater customisation and would make it not limited to being a C Engineer plugin.

**Comment by m0bilebtw** [comment]
This would be enabled by a change I'm already planning but don't currently have the time to implement - so I'll leave the issue open but don't want anyone to spend time on it just yet as it'll be changed by my planned changes anyway!

**Comment by m0bilebtw** [comment]
The change I was referring to has been implemented here: 8d200a3892cf5c685763c7f2b00b337f4d436951

This is not yet submitted as an update to the plugin hub, but when it is, and gets accepted, and your client updates the plugin install, there will be a folder in your .runelite folder full of the sounds this plugin uses. If you replace one of those sounds using the exact same file name, your replacement sound will be used. If you ever want to revert to the C Engineer sound, simply delete the file, and the plugin will replace it next time it starts.

I will keep this issue open until the plugin hub update including this change is submitted and accepted.

**Comment by m0bilebtw** [comment]
Plugin hub update submitted: runelite/plugin-hub#2515

**Comment by m0bilebtw** [comment]
This update has been accepted in to runelite plugin hub!
